import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Layout({children}) {

  return (
    <div className={styles.app}>
      <Head>
        <title>My Pokedex - App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        /* Fonts */
        
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
      </Head>

      <main className={styles.container}>
        {children}
      </main>

    </div>
  )
}